### ISSUE TITLE
EPIPE / ECONNRESET / Invalid move player packet received

### ISSUE THREAD

**Issue by Qaveru** [JadeMin/aterbot#10]
I had the bot working for all night, but when I joined server the bot disconnected and started trying to reconnect but was disconnected again and again giving me 2 errors in the console:

Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Framer.ondata (/home/runner/aternos-afkbot/node_modules/readable-stream/lib/internal/streams/readable.js:662:22)
    at Framer.emit (node:events:513:28) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
AFKBot got an error: Error: write ECONNRESET
Trying to reconnect in 15 seconds...

AFKBot logged in Sanitar

jump with sprinting
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

back with sprinting
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Framer.ondata (/home/runner/aternos-afkbot/node_modules/readable-stream/lib/internal/streams/readable.js:662:22)
    at Framer.emit (node:events:513:28) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by JadeMin** [comment]
Aternos may banned your bot. unban if in your server's ban list.

**Comment by Qaveru** [comment]
I changed nickname of the not and i worked, but it wasnt ban, more like smth else with "invalid move player packet received" error

**Comment by JadeMin** [comment]
## How do i fix ``invalid move player packet received``?
technically thats because your bot is in invalid pos or moving to invalid pos.
so first of all you have to wipe the bot's playerdata in your server.
1. go to your Aternos server management page and click `Files` in the left section
2. delete `world/playerdata/<UUID>.dat` and `<same>.dat_old` file that locates your bot's username.
**you will be lost your bot's data (such as inventory and last pos) in your server!**

if the problem happens repeatedly, lock your bot in some place

**Comment by Qaveru** [comment]
Yeah Ik its  not your codes fault. I Just closed my New bot in bedrock roomand it actually worked

**Comment by JadeMin** [comment]
alr good then i'll close this :)
