### ISSUE TITLE
Cannot read properties of undefined (reading 'overworld')

### ISSUE THREAD

**Issue by heyxferdi** [JadeMin/aterbot#64]
i have this problem when i `Run` the script
could anyone please help whats wrong?

## Describe your problem
```
TypeError: Cannot read properties of undefined (reading 'overworld')
    at handleRespawnPacketData (/home/runner/aterbot/node_modules/.pnpm/mineflayer@4.20.0/node_modules/mineflayer/lib/plugins/game.js:46:63)
    at Client.<anonymous> (/home/runner/aterbot/node_modules/.pnpm/mineflayer@4.20.0/node_modules/mineflayer/lib/plugins/game.js:80:5)
    at Client.emit (node:events:530:35)
    at Client.emit (node:domain:488:12)
    at emitPacket (/home/runner/aterbot/node_modules/.pnpm/minecraft-protocol@1.47.0/node_modules/minecraft-protocol/src/client.js:83:12)
    at FullPacketParser.<anonymous> (/home/runner/aterbot/node_modules/.pnpm/minecraft-protocol@1.47.0/node_modules/minecraft-protocol/src/client.js:112:9)
    at FullPacketParser.emit (node:events:518:28)
    at FullPacketParser.emit (node:domain:488:12)
    at addChunk (/home/runner/aterbot/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/home/runner/aterbot/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_readable.js:262:11)

Node.js v20.12.2
```

**Comment by JohannKili** [comment]
did you got it fixed or did you not do it any more @heyxferdi
