### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'overworld')

### ISSUE THREAD

**Issue by JohannKili** [JadeMin/aterbot#69]
```
TypeError: Cannot read properties of undefined (reading 'overworld')
    at handleRespawnPacketData (/home/runner/Aternos-247-V4/node_modules/.pnpm/mineflayer@4.10.1/node_modules/mineflayer/lib/plugins/game.js:46:47)
    at Client.<anonymous> (/home/runner/Aternos-247-V4/node_modules/.pnpm/mineflayer@4.10.1/node_modules/mineflayer/lib/plugins/game.js:75:5)
    at Client.emit (node:events:525:35)
    at Client.emit (node:domain:489:12)
    at emitPacket (/home/runner/Aternos-247-V4/node_modules/.pnpm/minecraft-protocol@1.43.1/node_modules/minecraft-protocol/src/client.js:83:12)
    at FullPacketParser.<anonymous> (/home/runner/Aternos-247-V4/node_modules/.pnpm/minecraft-protocol@1.43.1/node_modules/minecraft-protocol/src/client.js:106:9)
    at FullPacketParser.emit (node:events:513:28)
    at FullPacketParser.emit (node:domain:489:12)
    at addChunk (/home/runner/Aternos-247-V4/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/home/runner/Aternos-247-V4/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_readable.js:262:11)

Node.js v18.16.0
```

**Comment by Kartoshka2331** [comment]
https://socket.dev/npm/package/mineflayer-viaproxy
